Repository devschile/huemul, pull requests merged in 2018-10, with the labels that each got.

#469 fix(karma): excepciones excplícitas para el karma (p.ej, c++)
  scripts/karma.js
  test/karma.test.js
Labels: bugfix

#470 Se agrega soporte a rutjs para obtener rut de empresa
  scripts/rut.js
  test/rut.test.js
Labels: enhancement

#472 Se cambia fuente de noticias a ahoranoticias
  scripts/noticias.js
  test/noticias.test.js
Labels: bugfix

#475 fix(noticias): fix parse title
  scripts/noticias.js
Labels: bugfix

#474 Se corrige script saludo
  scripts/saluda.js
Labels: bugfix

#481 feat(map): add slack format
  scripts/map.js
Labels: enhancement

#483 correccion en los links de las imagenes
  scripts/dameundinosaurio.js
Labels: bugfix

#485 fix(horoscopo): add title
  scripts/horoscopo.js
Labels: bugfix

#487 deleted, malo el escrit :ql:
  scripts/demo.js
Labels: bug, hacktoberfest, wontfix

#488 Se evita emitir errores en info-rut
  package.json
  yarn.lock
Labels: bugfix
