Repository devschile/huemul, pull requests merged in 2018-09, with the labels that each got.

#451 fix(portadas): portadas Copesa, ajuste para HxH
  scripts/portadas.js
Labels: bugfix, enhancement

#452 updated keldors
  scripts/dameunkeldor.js
Labels: enhancement

#453 2 fixes: feriado & 18
  scripts/18.js
  scripts/proximo-feriado.js
Labels: bugfix, enhancement

#454 fix(deps): update bip to v3.0.2
  package.json
  yarn.lock
Labels: bugfix

#455 fix(patterns): add flag case insensitive
  scripts/calendario.js
  scripts/gardel.js
  scripts/word-blacklist.js
Labels: bugfix

#457 new(script)
  package.json
  scripts/dameunbackend.js
  scripts/horoscopo.js
  yarn.lock
Labels: new

#460 fix(horoscopo): make strict the coincidence of signs
  scripts/horoscopo.js
Labels: bugfix

#461 Feature/horoscopo
  package.json
  scripts/horoscopo.js
  yarn.lock
Labels: enhancement

#462 new(script)
  scripts/como-donar.js
Labels: new
