Repository devschile/huemul, pull requests merged in 2018-02, with the labels that each got.

#388 chore(paya): better paya by @claudrocker
  package.json
Labels: enhancement

#383 Feature/bitbucket status
  scripts/bitbucket-status.js
Labels: new

#389 new(script): linked from original repo, ES6'ized
  package.json
  scripts/cachipun.js
  yarn.lock
Labels: enhancement

#394 fix(js): added special characters
  scripts/vaporwave.js
Labels: bug
