Repository devschile/huemul, pull requests merged in 2018-08, with the labels that each got.

#444 feat(orionx): agrega luka
  scripts/orionx.js
Labels: enhancement

#446 new script
  scripts/dameunaexcusa.js
Labels: new

#449 fix(clima): remove all wrong characters
  scripts/clima.js
Labels: bugfix

#448 chore(js): better instructions && display max. 5 results
  scripts/temblor.js
Labels: bugfix, help wanted

#450 fix(js): .slice(0, 5) en slack environment
  scripts/quefumar.js
  scripts/temblor.js
Labels: bugfix
