Repository devschile/huemul, pull requests merged in 2019-10, with the labels that each got.

#584 better text for both scripts
  scripts/como-donar.js
  scripts/saluda.js
Labels: TAWENO, enhancement

#585 Se mejora el output del script como-donar
  scripts/como-donar.js
Labels: enhancement

#588 Se corrige test de nuevos cambios en karma
  package.json
  scripts/karma.js
  test/karma.test.js
  yarn.lock
Labels: bugfix

#590 Se corrige test de karma
  test/karma.test.js
Labels: bugfix
