Repository devschile/huemul, pull requests merged in 2020-10, with the labels that each got.

#637 fix(js): change query domain to search jobs
  README.md
  scripts/pegas.js
  test/pegas.test.js
Labels: bugfix

#639 fix(api): nueva api para horoscopos funcionando
  scripts/horoscopo.js
Labels: bugfix

#641 fix(date): better date handle and output
  scripts/18.js
  scripts/santoral.js
Labels: hacktoberfest-accepted

#642 chore(text): update text for gold script
  scripts/gold.js
Labels: enhancement

#644 chore(script): surbtc replaced, removed unused script
  external-scripts.json
  package.json
  scripts/como-donar.js
  scripts/saluda.js
  yarn.lock
Labels: dependencies, enhancement

#645 feat: add results for the plebiscito
  scripts/plebiscito2020.js
Labels: hacktoberfest-accepted, new

#646 feat(format): better output and count format
  scripts/plebiscito2020.js
Labels: enhancement, hacktoberfest-accepted
