Repository devschile/huemul, pull requests merged in 2022-10, with the labels that each got.

#712 fix(gardel): show explicit message for past days
  scripts/gardel.js
Labels: bugfix

#715 feat(fechas-importantes): agrega script para contar días hasta fecha
  .gitignore
  CODEOWNERS
  scripts/18.js
  scripts/fechas-importantes.js
Labels: new, hacktoberfest-2022

#717 feat(justwatch): allow use dónde ver / donde ver / ver
  scripts/justwatch.js
Labels: hacktoberfest-accepted

#716 Fix/karma tests
  scripts/helpers/client.js
  scripts/karma.js
  test/karma.test.js
  yarn.lock
Labels: hacktoberfest-2022

#718 feat(proverbios-chinos): añade script para obtener proverbios chinos
  scripts/proverbio-chino.js
Labels: new, hacktoberfest-2022

#721 feat(bin cl): agrega script para obtener códigos bin por banco chileno
  scripts/bin-checker.js
Labels: new, hacktoberfest-2022

#720 feat(beneficios): agrega script con beneficios para la comunidad
  scripts/beneficios-devschile.js
Labels: new, hacktoberfest-2022
